- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true

  vars:
    wharris_haproxy_load_balancer_packages:
      - haproxy
    wharris_haproxy_template: haproxy.cfg.j2
    wharris_haproxy_service: haproxy

  tags:
    - load_balancers

  tasks:

    - name: Install load balancer packages
      package:
        name: "{{ load_balancer_packages }}"
        state: present

    - name: Configure haproxy load balancing
      template:
        src: "{{ wharris_haproxy_template }}"
        dest: /etc/haproxy/haproxy.cfg
      notify: restart_haproxy

    - name: Enable Haproxy
      service:
        name: "{{ wharris_haproxy_service }}"
        state: started
        enabled: true

  handlers:

    - name: restart_haproxy
      service:
        name: "{{ wharris_haproxy_service }}"
        state: restarted