---
- name: Deploying Multi Tier App
  hosts: localhost
  gather_facts: false

- import_playbook: postgres.yml

- import_playbook: deploy-application.yml

- import_playbook: deploy-haproxy.yml

- import_playbook: smoke-test.yml

...
